In [ ]:
!pip install yfinance pandas numpy faiss-cpu sentence-transformers google-generativeai

Requirement already satisfied: yfinance in /usr/local/lib/python3.13/dist-packages (0.2.66)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.1.3)
Collecting faiss-cpu
  Downloading faiss_cpu-1.15.1-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.8 kB)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.13/dist-packages (5.7.0)
Collecting google-generativeai
  Downloading google_generativeai-0.8.6-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.13/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.13/dist-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from yfinance) (4.12.2)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.13/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.13/dist-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.13/dist-packages (from yfinance) (4.5.2)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.13/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.13/dist-packages (from yfinance) (0.16.3)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.13/dist-packages (from yfinance) (6.33.6)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.13/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from faiss-cpu) (26.3)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (5.18.0)
Requirement already satisfied: tokenizers>=0.19 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (0.23.2)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (1.33.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (2.11.0+cpu)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (4.16.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (4.67.3)
Collecting google-ai-generativelanguage==0.6.15 (from google-generativeai)
  Downloading google_ai_generativelanguage-0.6.15-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: google-api-core in /usr/local/lib/python3.13/dist-packages (from google-generativeai) (2.30.3)
Requirement already satisfied: google-api-python-client in /usr/local/lib/python3.13/dist-packages (from google-generativeai) (2.201.0)
Requirement already satisfied: google-auth>=2.15.0 in /usr/local/lib/python3.13/dist-packages (from google-generativeai) (2.49.0)
Requirement already satisfied: pydantic in /usr/local/lib/python3.13/dist-packages (from google-generativeai) (2.13.5)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /usr/local/lib/python3.13/dist-packages (from google-ai-generativelanguage==0.6.15->google-generativeai) (1.29.0)
Collecting protobuf>=3.19.0 (from yfinance)
  Downloading protobuf-5.29.6-cp38-abi3-manylinux2014_x86_64.whl.metadata (592 bytes)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.10)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from curl_cffi>=0.7->yfinance) (2.1.1)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.13/dist-packages (from curl_cffi>=0.7->yfinance) (2026.7.22)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in /usr/local/lib/python3.13/dist-packages (from google-api-core->google-generativeai) (1.75.5)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.13/dist-packages (from google-auth>=2.15.0->google-generativeai) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in /usr/local/lib/python3.13/dist-packages (from google-auth>=2.15.0->google-generativeai) (50.0.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.13/dist-packages (from google-auth>=2.15.0->google-generativeai) (4.9.1)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (4.0.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.31->yfinance) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.31->yfinance) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.7.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (3.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: typer in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.27.2)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /usr/local/lib/python3.13/dist-packages (from google-api-python-client->google-generativeai) (0.32.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from google-api-python-client->google-generativeai) (0.4.3)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.13/dist-packages (from google-api-python-client->google-generativeai) (4.2.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic->google-generativeai) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic->google-generativeai) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic->google-generativeai) (0.4.4)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=2.0.0->curl_cffi>=0.7->yfinance) (3.0)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.13/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.84.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.13/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.84.0)
INFO: pip is looking at multiple versions of googleapis-common-protos to determine which version is compatible with other requirements. This could take a while.
Collecting googleapis-common-protos<2.0.0,>=1.63.2 (from google-api-core->google-generativeai)
  Downloading googleapis_common_protos-1.75.4-py3-none-any.whl.metadata (8.5 kB)
  Downloading googleapis_common_protos-1.75.3-py3-none-any.whl.metadata (8.5 kB)
  Downloading googleapis_common_protos-1.75.2-py3-none-any.whl.metadata (8.5 kB)
  Downloading googleapis_common_protos-1.75.1-py3-none-any.whl.metadata (8.5 kB)
  Downloading googleapis_common_protos-1.75.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: pyparsing<4,>=3.1 in /usr/local/lib/python3.13/dist-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client->google-generativeai) (3.3.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.15.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn>=0.22.0->sentence-transformers) (3.1.2)
INFO: pip is looking at multiple versions of proto-plus to determine which version is compatible with other requirements. This could take a while.
Collecting proto-plus<2.0.0dev,>=1.22.3 (from google-ai-generativelanguage==0.6.15->google-generativeai)
  Downloading proto_plus-1.28.4-py3-none-any.whl.metadata (2.2 kB)
  Downloading proto_plus-1.28.3-py3-none-any.whl.metadata (2.2 kB)
  Downloading proto_plus-1.28.2-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.13/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-generativeai) (0.6.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.5)
INFO: pip is looking at multiple versions of grpcio-status to determine which version is compatible with other requirements. This could take a while.
Collecting grpcio-status<2.0.0,>=1.33.2 (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai)
  Downloading grpcio_status-1.83.1-py3-none-any.whl.metadata (1.2 kB)
  Downloading grpcio_status-1.83.0-py3-none-any.whl.metadata (1.2 kB)
  Downloading grpcio_status-1.82.2-py3-none-any.whl.metadata (1.2 kB)
  Downloading grpcio_status-1.82.1-py3-none-any.whl.metadata (1.2 kB)
  Downloading grpcio_status-1.81.1-py3-none-any.whl.metadata (1.2 kB)
  Downloading grpcio_status-1.81.0-py3-none-any.whl.metadata (1.2 kB)
  Downloading grpcio_status-1.80.0-py3-none-any.whl.metadata (1.3 kB)
INFO: pip is still looking at multiple versions of grpcio-status to determine which version is compatible with other requirements. This could take a while.
  Downloading grpcio_status-1.78.0-py3-none-any.whl.metadata (1.3 kB)
  Downloading grpcio_status-1.76.0-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.75.1-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.75.0-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.74.0-py3-none-any.whl.metadata (1.1 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Downloading grpcio_status-1.73.1-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.73.0-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.72.2-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.72.1-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.71.2-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)
Downloading faiss_cpu-1.15.1-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (18.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.8/18.8 MB 36.3 MB/s eta 0:00:00
Downloading google_generativeai-0.8.6-py3-none-any.whl (155 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.1/155.1 kB 7.4 MB/s eta 0:00:00
Downloading google_ai_generativelanguage-0.6.15-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 28.9 MB/s eta 0:00:00
Downloading protobuf-5.29.6-cp38-abi3-manylinux2014_x86_64.whl (320 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 320.5/320.5 kB 17.6 MB/s eta 0:00:00
Downloading googleapis_common_protos-1.75.0-py3-none-any.whl (300 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 300.6/300.6 kB 7.0 MB/s eta 0:00:00
Downloading proto_plus-1.28.2-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.7/50.7 kB 2.4 MB/s eta 0:00:00
Downloading grpcio_status-1.71.2-py3-none-any.whl (14 kB)
Installing collected packages: protobuf, faiss-cpu, proto-plus, googleapis-common-protos, grpcio-status, google-ai-generativelanguage, google-generativeai
  Attempting uninstall: protobuf
    Found existing installation: protobuf 6.33.6
    Uninstalling protobuf-6.33.6:
      Successfully uninstalled protobuf-6.33.6
  Attempting uninstall: proto-plus
    Found existing installation: proto-plus 1.29.0
    Uninstalling proto-plus-1.29.0:
      Successfully uninstalled proto-plus-1.29.0
  Attempting uninstall: googleapis-common-protos
    Found existing installation: googleapis-common-protos 1.75.5
    Uninstalling googleapis-common-protos-1.75.5:
      Successfully uninstalled googleapis-common-protos-1.75.5
  Attempting uninstall: grpcio-status
    Found existing installation: grpcio-status 1.84.0
    Uninstalling grpcio-status-1.84.0:
      Successfully uninstalled grpcio-status-1.84.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.21.0 requires protobuf<8.0.0,>=6.31.1, but you have protobuf 5.29.6 which is incompatible.
google-cloud-storage-control 1.15.0 requires protobuf<8.0.0,>=6.33.5, but you have protobuf 5.29.6 which is incompatible.
grpc-google-iam-v1 0.14.5 requires protobuf<8.0.0,>=6.33.5, but you have protobuf 5.29.6 which is incompatible.
google-cloud-dataproc 5.30.0 requires protobuf<8.0.0,>=6.33.5, but you have protobuf 5.29.6 which is incompatible.
google-cloud-spanner 3.71.0 requires protobuf<8.0.0,>=6.33.5, but you have protobuf 5.29.6 which is incompatible.
google-cloud-firestore 2.33.0 requires protobuf<8.0.0,>=6.33.5, but you have protobuf 5.29.6 which is incompatible.
tensorboard 2.21.0 requires protobuf<8.0.0,>=6.31.1, but you have protobuf 5.29.6 which is incompatible.
google-cloud-bigquery-storage 2.41.0 requires protobuf<8.0.0,>=6.33.5, but you have protobuf 5.29.6 which is incompatible.
google-cloud-datastore 2.26.1 requires protobuf<8.0.0,>=6.33.5, but you have protobuf 5.29.6 which is incompatible.
Successfully installed faiss-cpu-1.15.1 google-ai-generativelanguage-0.6.15 google-generativeai-0.8.6 googleapis-common-protos-1.75.0 grpcio-status-1.71.2 proto-plus-1.28.2 protobuf-5.29.6

In [ ]:
import yfinance as yf
import pandas as pd
import numpy as np

In [ ]:
ticker = yf.Ticker("AAPL")

In [ ]:
ticker.info

{'address1': 'One Apple Park Way',
 'city': 'Cupertino',
 'state': 'CA',
 'zip': '95014',
 'country': 'United States',
 'phone': '(408) 996-1010',
 'website': 'https://www.apple.com',
 'industry': 'Consumer Electronics',
 'industryKey': 'consumer-electronics',
 'industryDisp': 'Consumer Electronics',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple Vision Pro, Apple TV, Apple Watch, Beats products, and HomePod, as well as Apple branded and third-party accessories. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allows customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV, which offers original content and live sports; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers and resellers. The company was formerly known as Apple Computer, Inc. and changed its name to Apple Inc. in January 2007. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.',
 'fullTimeEmployees': 150000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Timothy D. Cook',
   'age': 64,
   'title': 'Executive Chairman of the Board',
   'yearBorn': 1961,
   'fiscalYear': 2025,
   'totalPay': 16759518,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Kevan  Parekh',
   'age': 53,
   'title': 'Senior VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4034174,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Sabih  Khan',
   'age': 58,
   'title': 'Senior VP & Chief Operating Officer',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5021905,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': "Ms. Deirdre  O'Brien",
   'age': 58,
   'title': 'Senior Vice President of Retail & People',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5037867,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Katherine L. Adams',
   'age': 61,
   'title': 'Secretary',
   'yearBorn': 1964,
   'fiscalYear': 2025,
   'totalPay': 5022482,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. John  Ternus',
   'age': 49,
   'title': 'CEO & Director',
   'yearBorn': 1976,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ben  Borders',
   'age': 44,
   'title': 'Principal Accounting Officer',
   'yearBorn': 1981,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Suhasini  Chandramouli',
   'title': 'Director of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Jennifer G. Newstead J.D.',
   'age': 55,
   'title': 'Senior VP of Government Affairs & General Counsel',
   'yearBorn': 1970,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Kristin Huguet Quayle',
   'title': 'Vice President of Worldwide Communications',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 2,
 'boardRisk': 3,
 'compensationRisk': 6,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1790812800,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://investor.apple.com/',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 336.67,
 'open': 336.83,
 'dayLow': 335.9,
 'dayHigh': 341.57,
 'regularMarketPreviousClose': 336.67,
 'regularMarketOpen': 336.83,
 'regularMarketDayLow': 335.9,
 'regularMarketDayHigh': 341.57,
 'dividendRate': 1.08,
 'dividendYield': 0.32,
 'exDividendDate': 1786320000,
 'payoutRatio': 0.1204,
 'fiveYearAvgDividendYield': 0.47,
 'beta': 1.069,
 'trailingPE': 39.03899,
 'forwardPE': 35.506687,
 'volume': 34459898,
 'regularMarketVolume': 34459898,
 'averageVolume': 45409914,
 'averageVolume10days': 34460570,
 'averageDailyVolume10Day': 34460570,
 'bid': 338.02,
 'ask': 342.47,
 'bidSize': 4,
 'askSize': 4,
 'marketCap': 4968150990848,
 'nonDilutedMarketCap': 4918530543600,
 'fiftyTwoWeekLow': 243.42,
 'fiftyTwoWeekHigh': 345.34,
 'allTimeHigh': 345.34,
 'allTimeLow': 0.049107,
 'fulldayPrice': 340.42,
 'fulldayChange': 3.9299927,
 'fulldayChangePercent': 1.167313,
 'priceToSalesTrailing12Months': 10.642473,
 'fiftyDayAverage': 322.2798,
 'twoHundredDayAverage': 290.08136,
 'trailingAnnualDividendRate': 1.05,
 'trailingAnnualDividendYield': 0.0031187807,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 4990095589376,
 'profitMargins': 0.27618998,
 'floatShares': 14568786127,
 'sharesOutstanding': 14594180000,
 'sharesShort': 128753092,
 'sharesShortPriorMonth': 116327753,
 'sharesShortPreviousMonthDate': 1786665600,
 'dateShortInterest': 1789430400,
 'sharesPercentSharesOut': 0.0088,
 'heldPercentInsiders': 0.016490001,
 'heldPercentInstitutions': 0.66321,
 'shortRatio': 3.03,
 'shortPercentOfFloat': 0.0088,
 'impliedSharesOutstanding': 14594180000,
 'bookValue': 7.36,
 'priceToBook': 46.25272,
 'lastFiscalYearEnd': 1758931200,
 'nextFiscalYearEnd': 1790467200,
 'mostRecentQuarter': 1782518400,
 'earningsQuarterlyGrowth': 0.271,
 'netIncomeToCommon': 128929996800,
 'trailingEps': 8.72,
 'forwardEps': 9.58749,
 'pegRatio': 2.69,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 1598832000,
 'enterpriseToRevenue': 10.689,
 'enterpriseToEbitda': 29.71,
 '52WeekChange': 0.32526374,
 'SandP52WeekChange': 0.15837312,
 'lastDividendValue': 0.27,
 'lastDividendDate': 1786320000,
 'quoteType': 'EQUITY',
 'currentPrice': 340.42,
 'targetHighPrice': 405.0,
 'targetLowPrice': 215.0,
 'targetMeanPrice': 328.09384,
 'targetMedianPrice': 340.0,
 'recommendationMean': 2.20455,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 39,
 'totalCash': 62399000576,
 'totalCashPerShare': 4.276,
 'ebitda': 167959003136,
 'totalDebt': 84343996416,
 'quickRatio': 0.812,
 'currentRatio': 1.003,
 'totalRevenue': 466822987776,
 'debtToEquity': 78.445,
 'revenuePerShare': 31.707,
 'returnOnAssets': 0.27082002,
 'returnOnEquity': 1.4875101,
 'grossProfits': 227123003392,
 'freeCashflow': 107721875456,
 'operatingCashflow': 146723995648,
 'earningsGrowth': 0.287,
 'revenueGrowth': 0.164,
 'grossMargins': 0.48653,
 'ebitdaMargins': 0.35979,
 'operatingMargins': 0.32623002,
 'financialCurrency': 'USD',
 'symbol': 'AAPL',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'fiftyTwoWeekLowChange': 97.000015,
 'fiftyTwoWeekLowChangePercent': 0.39848828,
 'fiftyTwoWeekRange': '243.42 - 345.34',
 'fiftyTwoWeekHighChange': -4.919983,
 'fiftyTwoWeekHighChangePercent': -0.0142467795,
 'fiftyTwoWeekChangePercent': 32.526375,
 'dividendDate': 1786579200,
 'earningsTimestamp': 1793649600,
 'earningsTimestampStart': 1793649600,
 'earningsTimestampEnd': 1793649600,
 'earningsCallTimestampStart': 1793656800,
 'earningsCallTimestampEnd': 1793656800,
 'isEarningsDateEstimate': False,
 'epsTrailingTwelveMonths': 8.72,
 'epsForward': 9.58749,
 'epsCurrentYear': 8.83135,
 'priceEpsCurrentYear': 38.54677,
 'fiftyDayAverageChange': 18.140228,
 'fiftyDayAverageChangePercent': 0.056287203,
 'twoHundredDayAverageChange': 50.338654,
 'twoHundredDayAverageChangePercent': 0.17353287,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 15,
 'averageAnalystRating': '2.2 - Buy',
 'cryptoTradeable': False,
 'corporateActions': [],
 'postMarketTime': 1791503997,
 'regularMarketTime': 1791489600,
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 345479400000,
 'postMarketChangePercent': 0.052873705,
 'postMarketPrice': 340.6,
 'postMarketChange': 0.17999268,
 'regularMarketChange': 3.75,
 'regularMarketChangePercent': 1.11385,
 'regularMarketPrice': 340.42,
 'regularMarketDayRange': '335.9 - 341.57',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 45409914,
 'shortName': 'Apple Inc.',
 'longName': 'Apple Inc.',
 'marketState': 'PREPRE',
 'exchange': 'NMS',
 'messageBoardId': 'finmb_24937',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'displayName': 'Apple',
 'trailingPegRatio': 2.706}

In [ ]:
print("Company Name:", ticker.info.get("longName"))
print("Sector:", ticker.info.get("sector"))
print("Industry:", ticker.info.get("industry"))

Company Name: Apple Inc.
Sector: Technology
Industry: Consumer Electronics

# **Collect Apple's financial statements**

In [ ]:
income_statement = ticker.income_stmt

income_statement.head()

,2025-09-30,2024-09-30,2023-09-30,2022-09-30
Tax Effect Of Unusual Items,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Tax Rate For Calcs,1.560000e-01,2.410000e-01,1.470000e-01,1.620000e-01
Normalized EBITDA,1.447480e+11,1.346610e+11,1.258200e+11,1.305410e+11
Net Income From Continuing Operation Net Minority Interest,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10
Reconciled Depreciation,1.169800e+10,1.144500e+10,1.151900e+10,1.110400e+10

In [ ]:
balance_sheet = ticker.balance_sheet

balance_sheet.head()

                          2025-09-30    2024-09-30    2023-09-30    2022-09-30
Treasury Shares Number           NaN           NaN  0.000000e+00           NaN
Ordinary Shares Number  1.477326e+10  1.511679e+10  1.555006e+10  1.594342e+10
Share Issued            1.477326e+10  1.511679e+10  1.555006e+10  1.594342e+10
Net Debt                6.272300e+10  7.668600e+10  8.112300e+10  9.642300e+10
Total Debt              9.865700e+10  1.066290e+11  1.110880e+11  1.324800e+11

In [ ]:
cash_flow = ticker.cashflow

cash_flow.head()

,2025-09-30,2024-09-30,2023-09-30,2022-09-30
Free Cash Flow,9.876700e+10,1.088070e+11,9.958400e+10,1.114430e+11
Repurchase Of Capital Stock,-9.071100e+10,-9.494900e+10,-7.755000e+10,-8.940200e+10
Repayment Of Debt,-1.093200e+10,-9.958000e+09,-1.115100e+10,-9.543000e+09
Issuance Of Debt,4.481000e+09,0.000000e+00,5.228000e+09,5.465000e+09
Capital Expenditure,-1.271500e+10,-9.447000e+09,-1.095900e+10,-1.070800e+10

In [ ]:
print("Income Statement:", income_statement.shape)
print("Balance Sheet:", balance_sheet.shape)
print("Cash Flow Statement:", cash_flow.shape)

Income Statement: (39, 4)
Balance Sheet: (69, 4)
Cash Flow Statement: (51, 4)

# **Collect historical stock prices and key financial metrics**

In [ ]:
historical_data = ticker.history(period="5y")

historical_data.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-10-11 00:00:00-04:00,138.766061,141.243497,138.317384,139.292755,64452200,0.0,0.0
2021-10-12 00:00:00-04:00,139.702374,139.721885,137.566309,138.024734,73035900,0.0,0.0
2021-10-13 00:00:00-04:00,137.761434,137.917482,135.771669,137.439560,78762700,0.0,0.0
2021-10-14 00:00:00-04:00,138.609974,140.336384,138.024745,140.219330,69907100,0.0,0.0
2021-10-15 00:00:00-04:00,140.229111,141.331271,139.975505,141.272751,67940300,0.0,0.0

In [ ]:
print("Historical data shape:", historical_data.shape)

Historical data shape: (1254, 7)

In [ ]:
info = ticker.info

metrics = {
    "Market Cap": info.get("marketCap"),
    "Current Price": info.get("currentPrice"),
    "Revenue": info.get("totalRevenue"),
    "Net Income": info.get("netIncomeToCommon"),
    "EPS": info.get("trailingEps"),
    "P/E Ratio": info.get("trailingPE"),
    "Price to Book": info.get("priceToBook"),
    "Return on Equity": info.get("returnOnEquity"),
    "Profit Margin": info.get("profitMargins"),
    "Operating Margin": info.get("operatingMargins"),
    "Debt to Equity": info.get("debtToEquity"),
    "Free Cash Flow": info.get("freeCashflow"),
}

metrics

{'Market Cap': 4968150990848,
 'Current Price': 340.42,
 'Revenue': 466822987776,
 'Net Income': 128929996800,
 'EPS': 8.72,
 'P/E Ratio': 39.03899,
 'Price to Book': 46.25272,
 'Return on Equity': 1.4875101,
 'Profit Margin': 0.27618998,
 'Operating Margin': 0.32623002,
 'Debt to Equity': 78.445,
 'Free Cash Flow': 107721875456}

In [ ]:
metrics_df = pd.DataFrame(
    metrics.items(),
    columns=["Metric", "Value"]
)

metrics_df

              Metric         Value
0         Market Cap  4.968151e+12
1      Current Price  3.404200e+02
2            Revenue  4.668230e+11
3         Net Income  1.289300e+11
4                EPS  8.720000e+00
5          P/E Ratio  3.903899e+01
6      Price to Book  4.625272e+01
7   Return on Equity  1.487510e+00
8      Profit Margin  2.761900e-01
9   Operating Margin  3.262300e-01
10    Debt to Equity  7.844500e+01
11    Free Cash Flow  1.077219e+11

# **Convert the financial data into text.**

In [ ]:
income_text = income_statement.to_string()

print(income_text[:3000])

                                                              2025-09-30    2024-09-30    2023-09-30    2022-09-30
Tax Effect Of Unusual Items                                 0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Tax Rate For Calcs                                          1.560000e-01  2.410000e-01  1.470000e-01  1.620000e-01
Normalized EBITDA                                           1.447480e+11  1.346610e+11  1.258200e+11  1.305410e+11
Net Income From Continuing Operation Net Minority Interest  1.120100e+11  9.373600e+10  9.699500e+10  9.980300e+10
Reconciled Depreciation                                     1.169800e+10  1.144500e+10  1.151900e+10  1.110400e+10
Reconciled Cost Of Revenue                                  2.209600e+11  2.103520e+11  2.141370e+11  2.235460e+11
EBITDA                                                      1.447480e+11  1.346610e+11  1.258200e+11  1.305410e+11
EBIT                                                        1.330500e+11  1.232160e+11  1.143010e+11  1.194370e+11
Net Interest Income                                                  NaN           NaN -1.830000e+08 -1.060000e+08
Interest Expense                                                     NaN           NaN  3.933000e+09  2.931000e+09
Interest Income                                                      NaN           NaN  3.750000e+09  2.825000e+09
Normalized Income                                           1.120100e+11  9.373600e+10  9.699500e+10  9.980300e+10
Net Income From Continuing And Discontinued Operation       1.120100e+11  9.373600e+10  9.699500e+10  9.980300e+10
Total Expenses                                              2.831110e+11  2.678190e+11  2.689840e+11  2.748910e+11
Total Operating Income As Reported                          1.330500e+11  1.232160e+11  1.143010e+11  1.194370e+11
Diluted Average Shares                                      1.500470e+10  1.540810e+10  1.581255e+10  1.632582e+10
Basic Average Shares                                        1.494850e+10  1.534378e+10  1.574423e+10  1.621596e+10
Diluted EPS                                                 7.460000e+00  6.080000e+00  6.130000e+00  6.110000e+00
Basic EPS                                                   7.490000e+00  6.110000e+00  6.160000e+00  6.150000e+00
Diluted NI Availto Com Stockholders                         1.120100e+11  9.373600e+10  9.699500e+10  9.980300e+10
Net Income Common Stockholders                              1.120100e+11  9.373600e+10  9.699500e+10  9.980300e+10
Net Income                                                  1.120100e+11  9.373600e+10  9.699500e+10  9.980300e+10
Net Income Including Noncontrolling Interests               1.120100e+11  9.373600e+10  9.699500e+10  9.980300e+10
Net Income Continuous Operations                            1.120100e+11  9.373600e+10  9.699500e+10  9.980300e+10
Tax Provision                                               2.071900e+10  2.974900e+10  1.674100e+10  1.930000e+10
Pretax Inc

In [ ]:
balance_text = balance_sheet.to_string()

print(balance_text[:3000])

                                                       2025-09-30    2024-09-30    2023-09-30    2022-09-30
Treasury Shares Number                                        NaN           NaN  0.000000e+00           NaN
Ordinary Shares Number                               1.477326e+10  1.511679e+10  1.555006e+10  1.594342e+10
Share Issued                                         1.477326e+10  1.511679e+10  1.555006e+10  1.594342e+10
Net Debt                                             6.272300e+10  7.668600e+10  8.112300e+10  9.642300e+10
Total Debt                                           9.865700e+10  1.066290e+11  1.110880e+11  1.324800e+11
Tangible Book Value                                  7.373300e+10  5.695000e+10  6.214600e+10  5.067200e+10
Invested Capital                                     1.723900e+11  1.635790e+11  1.732340e+11  1.707410e+11
Working Capital                                     -1.767400e+10 -2.340500e+10 -1.742000e+09 -1.857700e+10
Net Tangible Assets                                  7.373300e+10  5.695000e+10  6.214600e+10  5.067200e+10
Capital Lease Obligations                                     NaN           NaN  1.284200e+10  1.241100e+10
Common Stock Equity                                  7.373300e+10  5.695000e+10  6.214600e+10  5.067200e+10
Total Capitalization                                 1.520610e+11  1.427000e+11  1.574270e+11  1.496310e+11
Total Equity Gross Minority Interest                 7.373300e+10  5.695000e+10  6.214600e+10  5.067200e+10
Stockholders Equity                                  7.373300e+10  5.695000e+10  6.214600e+10  5.067200e+10
Gains Losses Not Affecting Retained Earnings        -5.571000e+09 -7.172000e+09 -1.145200e+10 -1.110900e+10
Other Equity Adjustments                            -5.571000e+09 -7.172000e+09 -1.145200e+10 -1.110900e+10
Retained Earnings                                   -1.426400e+10 -1.915400e+10 -2.140000e+08 -3.068000e+09
Capital Stock                                        9.356800e+10  8.327600e+10  7.381200e+10  6.484900e+10
Common Stock                                         9.356800e+10  8.327600e+10  7.381200e+10  6.484900e+10
Total Liabilities Net Minority Interest              2.855080e+11  3.080300e+11  2.904370e+11  3.020830e+11
Total Non Current Liabilities Net Minority Interest  1.198770e+11  1.316380e+11  1.451290e+11  1.481010e+11
Other Non Current Liabilities                        4.154900e+10  4.588800e+10  3.439100e+10  2.173700e+10
Tradeand Other Payables Non Current                           NaN  9.254000e+09  1.545700e+10  1.665700e+10
Long Term Debt And Capital Lease Obligation          7.832800e+10  8.575000e+10  9.528100e+10  1.097070e+11
Long Term Capital Lease Obligation                            NaN           NaN  1.126700e+10  1.074800e+10
Long Term Debt                                       7.832800e+10  8.575000e+10  9.528100e+10  9.895900e+10
Current Liabilities                                  1.656310e+11  1.763920e+11  1.4

In [ ]:
cashflow_text = cash_flow.to_string()

print(cashflow_text[:3000])

                                                  2025-09-30    2024-09-30    2023-09-30    2022-09-30
Free Cash Flow                                  9.876700e+10  1.088070e+11  9.958400e+10  1.114430e+11
Repurchase Of Capital Stock                    -9.071100e+10 -9.494900e+10 -7.755000e+10 -8.940200e+10
Repayment Of Debt                              -1.093200e+10 -9.958000e+09 -1.115100e+10 -9.543000e+09
Issuance Of Debt                                4.481000e+09  0.000000e+00  5.228000e+09  5.465000e+09
Capital Expenditure                            -1.271500e+10 -9.447000e+09 -1.095900e+10 -1.070800e+10
Interest Paid Supplemental Data                          NaN           NaN  3.803000e+09  2.865000e+09
Income Tax Paid Supplemental Data               4.336900e+10  2.610200e+10  1.867900e+10  1.957300e+10
End Cash Position                               3.593400e+10  2.994300e+10  3.073700e+10  2.497700e+10
Beginning Cash Position                         2.994300e+10  3.073700e+10  2.497700e+10  3.592900e+10
Changes In Cash                                 5.991000e+09 -7.940000e+08  5.760000e+09 -1.095200e+10
Financing Cash Flow                            -1.206860e+11 -1.219830e+11 -1.084880e+11 -1.107490e+11
Cash Flow From Continuing Financing Activities -1.206860e+11 -1.219830e+11 -1.084880e+11 -1.107490e+11
Net Other Financing Charges                    -6.071000e+09 -5.802000e+09 -6.012000e+09 -6.383000e+09
Cash Dividends Paid                            -1.542100e+10 -1.523400e+10 -1.502500e+10 -1.484100e+10
Common Stock Dividend Paid                     -1.542100e+10 -1.523400e+10 -1.502500e+10 -1.484100e+10
Net Common Stock Issuance                      -9.071100e+10 -9.494900e+10 -7.755000e+10 -8.940200e+10
Common Stock Payments                          -9.071100e+10 -9.494900e+10 -7.755000e+10 -8.940200e+10
Net Issuance Payments Of Debt                  -8.483000e+09 -5.998000e+09 -9.901000e+09 -1.230000e+08
Net Short Term Debt Issuance                   -2.032000e+09  3.960000e+09 -3.978000e+09  3.955000e+09
Net Long Term Debt Issuance                    -6.451000e+09 -9.958000e+09 -5.923000e+09 -4.078000e+09
Long Term Debt Payments                        -1.093200e+10 -9.958000e+09 -1.115100e+10 -9.543000e+09
Long Term Debt Issuance                         4.481000e+09  0.000000e+00  5.228000e+09  5.465000e+09
Investing Cash Flow                             1.519500e+10  2.935000e+09  3.705000e+09 -2.235400e+10
Cash Flow From Continuing Investing Activities  1.519500e+10  2.935000e+09  3.705000e+09 -2.235400e+10
Net Other Investing Changes                    -1.480000e+09 -1.308000e+09 -1.337000e+09 -2.086000e+09
Net Investment Purchase And Sale                2.939000e+10  1.369000e+10  1.600100e+10 -9.560000e+09
Sale Of Investment                              5.379700e+10  6.234600e+10  4.551400e+10  6.736300e+10
Purchase Of Investment                         -2.440700e+10 -4.865600e+10 -2.951300e+10 -7.692300e+10
Net Business

In [ ]:
historical_summary = historical_data.describe().to_string()

print(historical_summary)

              Open         High          Low        Close        Volume    Dividends  Stock Splits
count  1254.000000  1254.000000  1254.000000  1254.000000  1.254000e+03  1254.000000        1254.0
mean    203.315315   205.578726   201.312992   203.552578  6.335963e+07     0.003907           0.0
std      51.790739    52.277757    51.381060    51.870949  2.858368e+07     0.030764           0.0
min     123.800267   125.529397   121.992536   122.827621  1.791060e+07     0.000000           0.0
25%     163.719221   165.466764   162.345993   163.650394  4.470120e+07     0.000000           0.0
50%     189.140595   191.097134   187.890451   189.338287  5.486660e+07     0.000000           0.0
75%     235.620123   238.452066   232.682001   235.871006  7.491310e+07     0.000000           0.0
max     341.079987   345.339996   338.750000   341.070007  3.186799e+08     0.270000           0.0

In [ ]:
metrics_text = metrics_df.to_string(index=False)

print(metrics_text)

          Metric        Value
      Market Cap 4.968151e+12
   Current Price 3.404200e+02
         Revenue 4.668230e+11
      Net Income 1.289300e+11
             EPS 8.720000e+00
       P/E Ratio 3.903899e+01
   Price to Book 4.625272e+01
Return on Equity 1.487510e+00
   Profit Margin 2.761900e-01
Operating Margin 3.262300e-01
  Debt to Equity 7.844500e+01
  Free Cash Flow 1.077219e+11

# **Create our Financial Knowledge Base**

In [ ]:
financial_documents = []

financial_documents.append({
    "title": "Apple Income Statement",
    "content": income_text
})

financial_documents.append({
    "title": "Apple Balance Sheet",
    "content": balance_text
})

financial_documents.append({
    "title": "Apple Cash Flow Statement",
    "content": cashflow_text
})

financial_documents.append({
    "title": "Apple Historical Performance",
    "content": historical_summary
})

financial_documents.append({
    "title": "Apple Financial Metrics",
    "content": metrics_text
})

In [ ]:
print("Number of documents:", len(financial_documents))

Number of documents: 5

In [ ]:
print(financial_documents[0]["title"])
print(financial_documents[0]["content"][:2000])

Apple Income Statement
                                                              2025-09-30    2024-09-30    2023-09-30    2022-09-30
Tax Effect Of Unusual Items                                 0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Tax Rate For Calcs                                          1.560000e-01  2.410000e-01  1.470000e-01  1.620000e-01
Normalized EBITDA                                           1.447480e+11  1.346610e+11  1.258200e+11  1.305410e+11
Net Income From Continuing Operation Net Minority Interest  1.120100e+11  9.373600e+10  9.699500e+10  9.980300e+10
Reconciled Depreciation                                     1.169800e+10  1.144500e+10  1.151900e+10  1.110400e+10
Reconciled Cost Of Revenue                                  2.209600e+11  2.103520e+11  2.141370e+11  2.235460e+11
EBITDA                                                      1.447480e+11  1.346610e+11  1.258200e+11  1.305410e+11
EBIT                                                        1.330500e+11  1.232160e+11  1.143010e+11  1.194370e+11
Net Interest Income                                                  NaN           NaN -1.830000e+08 -1.060000e+08
Interest Expense                                                     NaN           NaN  3.933000e+09  2.931000e+09
Interest Income                                                      NaN           NaN  3.750000e+09  2.825000e+09
Normalized Income                                           1.120100e+11  9.373600e+10  9.699500e+10  9.980300e+10
Net Income From Continuing And Discontinued Operation       1.120100e+11  9.373600e+10  9.699500e+10  9.980300e+10
Total Expenses                                              2.831110e+11  2.678190e+11  2.689840e+11  2.748910e+11
Total Operating Income As Reported                          1.330500e+11  1.232160e+11  1.143010e+11  1.194370e+11
Diluted Average Shares                                      1.500470e+10  1.540810e+10  1.581255e+10  1.632582e+10
Basic Average Shares

# **Text Chunking for the RAG Knowledge Base**

In [ ]:
!pip install langchain

Requirement already satisfied: langchain in /usr/local/lib/python3.13/dist-packages (1.4.3)
Requirement already satisfied: langchain-core<2.0.0,>=1.6.3 in /usr/local/lib/python3.13/dist-packages (from langchain) (1.6.6)
Requirement already satisfied: langgraph<1.3.0,>=1.2.11 in /usr/local/lib/python3.13/dist-packages (from langchain) (1.2.12)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.13/dist-packages (from langchain) (2.13.5)
Requirement already satisfied: httpx<1.0.0,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (0.28.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (0.0.19)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (0.14.2)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (26.3)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (4.16.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.6.3->langchain) (0.17.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from langgraph<1.3.0,>=1.2.11->langchain) (4.2.0)
Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from langgraph<1.3.0,>=1.2.11->langchain) (1.1.0)
Requirement already satisfied: langgraph-sdk<0.5.0,>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from langgraph<1.3.0,>=1.2.11->langchain) (0.4.5)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.13/dist-packages (from langgraph<1.3.0,>=1.2.11->langchain) (4.0.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.6.3->langchain) (4.15.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.6.3->langchain) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.6.3->langchain) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.6.3->langchain) (3.20)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.6.3->langchain) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.13/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.6.3->langchain) (3.1.1)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.13/dist-packages (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.11->langchain) (1.12.2)
Requirement already satisfied: orjson>=3.11.5 in /usr/local/lib/python3.13/dist-packages (from langgraph-sdk<0.5.0,>=0.4.2->langgraph<1.3.0,>=1.2.11->langchain) (3.12.0)
Requirement already satisfied: websockets<17,>=14 in /usr/local/lib/python3.13/dist-packages (from langgraph-sdk<0.5.0,>=0.4.2->langgraph<1.3.0,>=1.2.11->langchain) (15.0.1)
Requirement already satisfied: distro>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (1.9.0)
Requirement already satisfied: httpx2<3,>=2 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (2.13.1)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (2.32.4)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (1.3.1)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (0.25.0)
Requirement already satisfied: httpcore2==2.13.1 in /usr/local/lib/python3.13/dist-packages (from httpx2<3,>=2->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (2.13.1)
Requirement already satisfied: truststore>=0.10 in /usr/local/lib/python3.13/dist-packages (from httpx2<3,>=2->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (0.10.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.3->langchain) (2.5.0)

In [ ]:
!pip install -U langchain-text-splitters

Collecting langchain-text-splitters
  Downloading langchain_text_splitters-1.1.3-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.4.7 in /usr/local/lib/python3.13/dist-packages (from langchain-text-splitters) (1.6.6)
Requirement already satisfied: httpx<1.0.0,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (0.28.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (0.0.19)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (0.14.2)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (26.3)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (2.13.5)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (4.16.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.13/dist-packages (from langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (0.17.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (4.15.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (3.20)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.13/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (3.1.1)
Requirement already satisfied: distro>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (1.9.0)
Requirement already satisfied: httpx2<3,>=2 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (2.13.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (3.12.0)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (2.32.4)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (1.3.1)
Requirement already satisfied: websockets>=15.0 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (15.0.1)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (4.0.1)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (0.4.4)
Requirement already satisfied: httpcore2==2.13.1 in /usr/local/lib/python3.13/dist-packages (from httpx2<3,>=2->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (2.13.1)
Requirement already satisfied: truststore>=0.10 in /usr/local/lib/python3.13/dist-packages (from httpx2<3,>=2->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (0.10.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (2.5.0)
Downloading langchain_text_splitters-1.1.3-py3-none-any.whl (38 kB)
Installing collected packages: langchain-text-splitters
Successfully installed langchain-text-splitters-1.1.3

In [ ]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

In [ ]:
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200
)

In [ ]:
all_text = ""

for document in financial_documents:
    all_text += document["title"] + "\n"
    all_text += document["content"] + "\n\n"

In [ ]:
chunks = text_splitter.split_text(all_text)

In [ ]:
print("Number of chunks:", len(chunks))

Number of chunks: 24

In [ ]:
print(chunks[20])

Change In Payable                               9.020000e+08  6.020000e+09 -1.889000e+09  9.448000e+09
Change In Account Payable                       9.020000e+08  6.020000e+09 -1.889000e+09  9.448000e+09
Change In Inventory                             1.400000e+09 -1.046000e+09 -1.618000e+09  1.484000e+09
Change In Receivables                          -7.029000e+09 -5.144000e+09 -4.170000e+08 -9.343000e+09
Changes In Account Receivables                 -6.682000e+09 -3.788000e+09 -1.688000e+09 -1.823000e+09
Other Non Cash Items                           -8.900000e+07 -2.266000e+09 -2.227000e+09  1.006000e+09
Stock Based Compensation                        1.286300e+10  1.168800e+10  1.083300e+10  9.038000e+09
Deferred Tax                                             NaN           NaN           NaN  8.950000e+08
Deferred Income Tax                                      NaN           NaN           NaN  8.950000e+08

In [ ]:
print("Number of chunks:", len(chunks))

Number of chunks: 24

# **Generate embeddings**

In [ ]:
!pip install -U sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.13/dist-packages (5.7.0)
Collecting sentence-transformers
  Downloading sentence_transformers-6.1.0-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: transformers<6.0.0,>=5.0.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (5.18.0)
Requirement already satisfied: tokenizers>=0.19 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (0.23.2)
Requirement already satisfied: huggingface-hub<2.0.0,>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (1.33.0)
Requirement already satisfied: torch>=2.2 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (2.11.0+cpu)
Requirement already satisfied: numpy>=1.24.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (2.1.3)
Requirement already satisfied: scikit-learn>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (4.16.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (4.0.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (2025.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (6.0.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.1.0->sentence-transformers) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.1.0->sentence-transformers) (3.7.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2->sentence-transformers) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2->sentence-transformers) (3.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2->sentence-transformers) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: typer in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (0.27.2)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (0.8.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (4.15.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (3.20)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.16.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn>=1.1.0->sentence-transformers) (3.1.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch>=2.2->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=2.2->sentence-transformers) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (0.0.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (0.1.2)
Downloading sentence_transformers-6.1.0-py3-none-any.whl (740 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 740.6/740.6 kB 37.1 MB/s eta 0:00:00
Installing collected packages: sentence-transformers
  Attempting uninstall: sentence-transformers
    Found existing installation: sentence-transformers 5.7.0
    Uninstalling sentence-transformers-5.7.0:
      Successfully uninstalled sentence-transformers-5.7.0
Successfully installed sentence-transformers-6.1.0

In [ ]:
from sentence_transformers import SentenceTransformer

In [ ]:
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

In [ ]:
embeddings = embedding_model.encode(chunks)

In [ ]:
print("Number of chunks:", len(chunks))
print("Embedding shape:", embeddings.shape)

Number of chunks: 24
Embedding shape: (24, 384)

# **Creating the FAISS vector database**

In [ ]:
!pip install faiss-cpu

Requirement already satisfied: faiss-cpu in /usr/local/lib/python3.13/dist-packages (1.15.1)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.13/dist-packages (from faiss-cpu) (2.1.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from faiss-cpu) (26.3)

In [ ]:
import faiss

In [ ]:
dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)

In [ ]:
index.add(embeddings.astype("float32"))

In [ ]:
print("Number of vectors in FAISS:", index.ntotal)

Number of vectors in FAISS: 24

# **Search FAISS**

In [ ]:
question = "What is Apple's net income?"

In [ ]:
question_embedding = embedding_model.encode([question])

In [ ]:
distances, indices = index.search(
    question_embedding.astype("float32"),
    k=3
)

In [ ]:
for i in indices[0]:
    print("----- Retrieved Chunk -----")
    print(chunks[i])

----- Retrieved Chunk -----
Apple Financial Metrics
          Metric        Value
      Market Cap 4.913423e+12
   Current Price 3.366700e+02
         Revenue 4.668230e+11
      Net Income 1.289300e+11
             EPS 8.720000e+00
       P/E Ratio 3.860894e+01
   Price to Book 4.574321e+01
Return on Equity 1.487510e+00
   Profit Margin 2.761900e-01
Operating Margin 3.262300e-01
  Debt to Equity 7.844500e+01
  Free Cash Flow 1.077219e+11
----- Retrieved Chunk -----
Apple Income Statement
                                                              2025-09-30    2024-09-30    2023-09-30    2022-09-30
Tax Effect Of Unusual Items                                 0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Tax Rate For Calcs                                          1.560000e-01  2.410000e-01  1.470000e-01  1.620000e-01
Normalized EBITDA                                           1.447480e+11  1.346610e+11  1.258200e+11  1.305410e+11
Net Income From Continuing Operation Net Minority Interest  1.120100e+11  9.373600e+10  9.699500e+10  9.980300e+10
Reconciled Depreciation                                     1.169800e+10  1.144500e+10  1.151900e+10  1.110400e+10
Reconciled Cost Of Revenue                                  2.209600e+11  2.103520e+11  2.141370e+11  2.235460e+11
EBITDA                                                      1.447480e+11  1.346610e+11  1.258200e+11  1.305410e+11
----- Retrieved Chunk -----
Apple Cash Flow Statement
                                                  2025-09-30    2024-09-30    2023-09-30    2022-09-30
Free Cash Flow                                  9.876700e+10  1.088070e+11  9.958400e+10  1.114430e+11
Repurchase Of Capital Stock                    -9.071100e+10 -9.494900e+10 -7.755000e+10 -8.940200e+10
Repayment Of Debt                              -1.093200e+10 -9.958000e+09 -1.115100e+10 -9.543000e+09
Issuance Of Debt                                4.481000e+09  0.000000e+00  5.228000e+09  5.465000e+09
Capital Expenditure                            -1.271500e+10 -9.447000e+09 -1.095900e+10 -1.070800e+10
Interest Paid Supplemental Data                          NaN           NaN  3.803000e+09  2.865000e+09
Income Tax Paid Supplemental Data               4.336900e+10  2.610200e+10  1.867900e+10  1.957300e+10
End Cash Position                               3.593400e+10  2.994300e+10  3.073700e+10  2.497700e+10

# **Connect Gemini**

In [ ]:
!pip install -U google-generativeai

import google.generativeai as genai

Collecting google-generativeai
  Downloading google_generativeai-0.8.6-py3-none-any.whl.metadata (3.9 kB)
Collecting google-ai-generativelanguage==0.6.15 (from google-generativeai)
  Downloading google_ai_generativelanguage-0.6.15-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: google-api-core in /usr/local/lib/python3.13/dist-packages (from google-generativeai) (2.30.3)
Requirement already satisfied: google-api-python-client in /usr/local/lib/python3.13/dist-packages (from google-generativeai) (2.201.0)
Requirement already satisfied: google-auth>=2.15.0 in /usr/local/lib/python3.13/dist-packages (from google-generativeai) (2.49.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from google-generativeai) (6.33.6)
Requirement already satisfied: pydantic in /usr/local/lib/python3.13/dist-packages (from google-generativeai) (2.13.5)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from google-generativeai) (4.67.3)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.13/dist-packages (from google-generativeai) (4.16.0)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /usr/local/lib/python3.13/dist-packages (from google-ai-generativelanguage==0.6.15->google-generativeai) (1.29.0)
Collecting protobuf (from google-generativeai)
  Downloading protobuf-5.29.6-cp38-abi3-manylinux2014_x86_64.whl.metadata (592 bytes)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in /usr/local/lib/python3.13/dist-packages (from google-api-core->google-generativeai) (1.75.5)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /usr/local/lib/python3.13/dist-packages (from google-api-core->google-generativeai) (2.32.4)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.13/dist-packages (from google-auth>=2.15.0->google-generativeai) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in /usr/local/lib/python3.13/dist-packages (from google-auth>=2.15.0->google-generativeai) (50.0.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.13/dist-packages (from google-auth>=2.15.0->google-generativeai) (4.9.1)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /usr/local/lib/python3.13/dist-packages (from google-api-python-client->google-generativeai) (0.32.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from google-api-python-client->google-generativeai) (0.4.3)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.13/dist-packages (from google-api-python-client->google-generativeai) (4.2.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic->google-generativeai) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic->google-generativeai) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic->google-generativeai) (0.4.4)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from cryptography>=38.0.3->google-auth>=2.15.0->google-generativeai) (2.1.1)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.13/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.84.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.13/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.84.0)
INFO: pip is looking at multiple versions of googleapis-common-protos to determine which version is compatible with other requirements. This could take a while.
Collecting googleapis-common-protos<2.0.0,>=1.63.2 (from google-api-core->google-generativeai)
  Downloading googleapis_common_protos-1.75.4-py3-none-any.whl.metadata (8.5 kB)
  Downloading googleapis_common_protos-1.75.3-py3-none-any.whl.metadata (8.5 kB)
  Downloading googleapis_common_protos-1.75.2-py3-none-any.whl.metadata (8.5 kB)
  Downloading googleapis_common_protos-1.75.1-py3-none-any.whl.metadata (8.5 kB)
  Downloading googleapis_common_protos-1.75.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: pyparsing<4,>=3.1 in /usr/local/lib/python3.13/dist-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client->google-generativeai) (3.3.3)
INFO: pip is looking at multiple versions of proto-plus to determine which version is compatible with other requirements. This could take a while.
Collecting proto-plus<2.0.0dev,>=1.22.3 (from google-ai-generativelanguage==0.6.15->google-generativeai)
  Downloading proto_plus-1.28.4-py3-none-any.whl.metadata (2.2 kB)
  Downloading proto_plus-1.28.3-py3-none-any.whl.metadata (2.2 kB)
  Downloading proto_plus-1.28.2-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.13/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-generativeai) (0.6.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core->google-generativeai) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core->google-generativeai) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core->google-generativeai) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core->google-generativeai) (2026.7.22)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth>=2.15.0->google-generativeai) (3.0)
INFO: pip is looking at multiple versions of grpcio-status to determine which version is compatible with other requirements. This could take a while.
Collecting grpcio-status<2.0.0,>=1.33.2 (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai)
  Downloading grpcio_status-1.83.1-py3-none-any.whl.metadata (1.2 kB)
  Downloading grpcio_status-1.83.0-py3-none-any.whl.metadata (1.2 kB)
  Downloading grpcio_status-1.82.2-py3-none-any.whl.metadata (1.2 kB)
  Downloading grpcio_status-1.82.1-py3-none-any.whl.metadata (1.2 kB)
  Downloading grpcio_status-1.81.1-py3-none-any.whl.metadata (1.2 kB)
  Downloading grpcio_status-1.81.0-py3-none-any.whl.metadata (1.2 kB)
  Downloading grpcio_status-1.80.0-py3-none-any.whl.metadata (1.3 kB)
INFO: pip is still looking at multiple versions of grpcio-status to determine which version is compatible with other requirements. This could take a while.
  Downloading grpcio_status-1.78.0-py3-none-any.whl.metadata (1.3 kB)
  Downloading grpcio_status-1.76.0-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.75.1-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.75.0-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.74.0-py3-none-any.whl.metadata (1.1 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Downloading grpcio_status-1.73.1-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.73.0-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.72.2-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.72.1-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.71.2-py3-none-any.whl.metadata (1.1 kB)
Downloading google_generativeai-0.8.6-py3-none-any.whl (155 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.1/155.1 kB 4.1 MB/s eta 0:00:00
Downloading google_ai_generativelanguage-0.6.15-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 21.3 MB/s eta 0:00:00
Downloading protobuf-5.29.6-cp38-abi3-manylinux2014_x86_64.whl (320 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 320.5/320.5 kB 6.3 MB/s eta 0:00:00
Downloading googleapis_common_protos-1.75.0-py3-none-any.whl (300 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 300.6/300.6 kB 7.9 MB/s eta 0:00:00
Downloading proto_plus-1.28.2-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.7/50.7 kB 1.1 MB/s eta 0:00:00
Downloading grpcio_status-1.71.2-py3-none-any.whl (14 kB)
Installing collected packages: protobuf, proto-plus, googleapis-common-protos, grpcio-status, google-ai-generativelanguage, google-generativeai
  Attempting uninstall: protobuf
    Found existing installation: protobuf 6.33.6
    Uninstalling protobuf-6.33.6:
      Successfully uninstalled protobuf-6.33.6
  Attempting uninstall: proto-plus
    Found existing installation: proto-plus 1.29.0
    Uninstalling proto-plus-1.29.0:
      Successfully uninstalled proto-plus-1.29.0
  Attempting uninstall: googleapis-common-protos
    Found existing installation: googleapis-common-protos 1.75.5
    Uninstalling googleapis-common-protos-1.75.5:
      Successfully uninstalled googleapis-common-protos-1.75.5
  Attempting uninstall: grpcio-status
    Found existing installation: grpcio-status 1.84.0
    Uninstalling grpcio-status-1.84.0:
      Successfully uninstalled grpcio-status-1.84.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.21.0 requires protobuf<8.0.0,>=6.31.1, but you have protobuf 5.29.6 which is incompatible.
google-cloud-storage-control 1.15.0 requires protobuf<8.0.0,>=6.33.5, but you have protobuf 5.29.6 which is incompatible.
grpc-google-iam-v1 0.14.5 requires protobuf<8.0.0,>=6.33.5, but you have protobuf 5.29.6 which is incompatible.
google-cloud-dataproc 5.30.0 requires protobuf<8.0.0,>=6.33.5, but you have protobuf 5.29.6 which is incompatible.
google-cloud-spanner 3.71.0 requires protobuf<8.0.0,>=6.33.5, but you have protobuf 5.29.6 which is incompatible.
google-cloud-firestore 2.33.0 requires protobuf<8.0.0,>=6.33.5, but you have protobuf 5.29.6 which is incompatible.
tensorboard 2.21.0 requires protobuf<8.0.0,>=6.31.1, but you have protobuf 5.29.6 which is incompatible.
google-cloud-bigquery-storage 2.41.0 requires protobuf<8.0.0,>=6.33.5, but you have protobuf 5.29.6 which is incompatible.
google-cloud-datastore 2.26.1 requires protobuf<8.0.0,>=6.33.5, but you have protobuf 5.29.6 which is incompatible.
Successfully installed google-ai-generativelanguage-0.6.15 google-generativeai-0.8.6 googleapis-common-protos-1.75.0 grpcio-status-1.71.2 proto-plus-1.28.2 protobuf-5.29.6

/tmp/ipykernel_1056/2204206780.py:3: FutureWarning:

All support for the `google.generativeai` package has ended. It will no longer be receiving
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  import google.generativeai as genai

In [ ]:
from google.colab import userdata
import google.generativeai as genai

api_key = userdata.get("GEMINI_API_KEY")
genai.configure(api_key=api_key)

In [ ]:
model = genai.GenerativeModel("gemini-3.8-flash")

In [ ]:
response = model.generate_content("What is Apple's net income?")
print(response.text)

For its most recent full fiscal year (**Fiscal Year 2024**, ended September 28, 2024), Apple reported a net income of **$93.74 billion** (down slightly from $96.99 billion in FY 2023, largely due to a one-time $10.2 billion European tax charge).

### Recent Breakdown:
* **Fiscal Year 2024 (Full Year):** $93.74 billion
* **Fiscal Year 2023 (Full Year):** $96.995 billion
* **Most Recent Quarter (Q1 FY25, ended Dec 28, 2024):** $36.33 billion

# **Combine FAISS + Gemini**

In [ ]:
question = "What is Apple's net income?"

question_embedding = embedding_model.encode([question])

distances, indices = index.search(
    question_embedding.astype("float32"),
    k=3
)

retrieved_context = ""

for i in indices[0]:
    retrieved_context += chunks[i] + "\n\n"

prompt = f"""
Answer the question using ONLY the financial information provided below.

Financial Information:
{retrieved_context}

Question:
{question}

If the information is not available in the provided financial information, say:
"Information not available in the provided data."

Do not use outside information.
"""

response = model.generate_content(prompt)

print(response.text)

Based on the provided financial information:

* Under **Apple Financial Metrics**, Apple's **Net Income** is **1.289300e+11** (or approximately $128.93 billion).

Additionally, under the **Apple Income Statement**, **Net Income From Continuing Operation Net Minority Interest** is reported as:
* **2025-09-30:** 1.120100e+11
* **2024-09-30:** 9.373600e+10
* **2023-09-30:** 9.699500e+10
* **2022-09-30:** 9.980300e+10

In [ ]:
question = "What is Apple's revenue?"

question_embedding = embedding_model.encode([question])

distances, indices = index.search(
    question_embedding.astype("float32"),
    k=3
)

retrieved_context = ""

for i in indices[0]:
    retrieved_context += chunks[i] + "\n\n"

prompt = f"""
Answer the question using ONLY the financial information provided below.

Financial Information:
{retrieved_context}

Question:
{question}

If the information is not available in the provided financial information, say:
"Information not available in the provided data."

Do not use outside information.
"""

response = model.generate_content(prompt)

print(response.text)

Based on the provided financial information, Apple's revenue is **4.668230e+11** (or $466,823,000,000).

In [ ]:
question = "What is Apple's EPS?"

question_embedding = embedding_model.encode([question])

distances, indices = index.search(
    question_embedding.astype("float32"),
    k=3
)

retrieved_context = ""

for i in indices[0]:
    retrieved_context += chunks[i] + "\n\n"

prompt = f"""
Answer the question using ONLY the financial information provided below.

Financial Information:
{retrieved_context}

Question:
{question}

If the information is not available in the provided financial information, say:
"Information not available in the provided data."

Do not use outside information.
"""

response = model.generate_content(prompt)

print(response.text)

Based on the provided financial information, Apple's EPS is **8.72** (or 8.720000e+00).

In [ ]:
question = "What is Apple's debt and cash position?"

question_embedding = embedding_model.encode([question])

distances, indices = index.search(
    question_embedding.astype("float32"),
    k=3
)

retrieved_context = ""

for i in indices[0]:
    retrieved_context += chunks[i] + "\n\n"

prompt = f"""
Answer the question using ONLY the financial information provided below.

Financial Information:
{retrieved_context}

Question:
{question}

If the information is not available in the provided financial information, say:
"Information not available in the provided data."

Do not use outside information.
"""

response = model.generate_content(prompt)

print(response.text)

Based on the provided financial information, Apple's debt and cash positions across the reported periods are as follows:

### **Cash Position (End Cash Position)**
* **2025-09-30:** 3.593400e+10 (~$35.93 billion)
* **2024-09-30:** 2.994300e+10 (~$29.94 billion)
* **2023-09-30:** 3.073700e+10 (~$30.74 billion)
* **2022-09-30:** 2.497700e+10 (~$24.98 billion)

---

### **Debt Position**
* **Total Debt:**
  * **2025-09-30:** 9.865700e+10 (~$98.66 billion)
  * **2024-09-30:** 1.066290e+11 (~$106.63 billion)
  * **2023-09-30:** 1.110880e+11 (~$111.09 billion)
  * **2022-09-30:** 1.324800e+11 (~$132.48 billion)

* **Net Debt:**
  * **2025-09-30:** 6.272300e+10 (~$62.72 billion)
  * **2024-09-30:** 7.668600e+10 (~$76.69 billion)
  * **2023-09-30:** 8.112300e+10 (~$81.12 billion)
  * **2022-09-30:** 9.642300e+10 (~$96.42 billion)

* **Debt to Equity Ratio:** 7.844500e+01 (78.445)

In [ ]:
question = "What is Apple's free cash flow?"

question_embedding = embedding_model.encode([question])

distances, indices = index.search(
    question_embedding.astype("float32"),
    k=3
)

retrieved_context = ""

for i in indices[0]:
    retrieved_context += chunks[i] + "\n\n"

prompt = f"""
Answer the question using ONLY the financial information provided below.

Financial Information:
{retrieved_context}

Question:
{question}

If the information is not available in the provided financial information, say:
"Information not available in the provided data."

Do not use outside information.
"""

response = model.generate_content(prompt)

print(response.text)

Based on the provided financial information, Apple's Free Cash Flow is reported as follows:

* **Under Apple Financial Metrics:**
  * **Free Cash Flow:** 1.077219e+11 (or approximately $107.72 billion)

* **Under Apple Cash Flow Statement (by fiscal year):**
  * **2025-09-30:** 9.876700e+10 (or approximately $98.77 billion)
  * **2024-09-30:** 1.088070e+11 (or approximately $108.81 billion)
  * **2023-09-30:** 9.958400e+10 (or approximately $99.58 billion)
  * **2022-09-30:** 1.114430e+11 (or approximately $111.44 billion)

# **Test Financial Ratios**

In [ ]:
question = "What are Apple's financial ratios, including P/E ratio, Price-to-Book ratio, Return on Equity, Profit Margin, and Operating Margin?"

question_embedding = embedding_model.encode([question])

distances, indices = index.search(
    question_embedding.astype("float32"),
    k=3
)

retrieved_context = ""

for i in indices[0]:
    retrieved_context += chunks[i] + "\n\n"

prompt = f"""
Answer the question using ONLY the financial information provided below.

Financial Information:
{retrieved_context}

Question:
{question}

If the information is not available in the provided financial information, say:
"Information not available in the provided data."

Do not use outside information.
"""

response = model.generate_content(prompt)

print(response.text)

Based on the provided financial information, Apple's financial ratios are:

* **P/E Ratio:** 3.903899e+01 (or approximately 39.04)
* **Price to Book:** 4.625272e+01 (or approximately 46.25)
* **Return on Equity:** 1.487510e+00 (or approximately 1.488 / 148.75%)
* **Profit Margin:** 2.761900e-01 (or approximately 0.276 / 27.62%)
* **Operating Margin:** 3.262300e-01 (or approximately 0.326 / 32.62%)

In [ ]:
question = "What are Apple's total assets, total liabilities, and total debt?"

question_embedding = embedding_model.encode([question])

distances, indices = index.search(
    question_embedding.astype("float32"),
    k=3
)

retrieved_context = ""

for i in indices[0]:
    retrieved_context += chunks[i] + "\n\n"

prompt = f"""
Answer the question using ONLY the financial information provided below.

Financial Information:
{retrieved_context}

Question:
{question}

If the information is not available in the provided financial information, say:
"Information not available in the provided data."

Do not use outside information.
"""

response = model.generate_content(prompt)

print(response.text)

Based on the provided financial information:

* **Total Assets:** Information not available in the provided data.
* **Total Liabilities:** Information not available in the provided data.
* **Total Debt:**
  * **2025-09-30:** 9.865700e+10 ($98.657 billion)
  * **2024-09-30:** 1.066290e+11 ($106.629 billion)
  * **2023-09-30:** 1.110880e+11 ($111.088 billion)
  * **2022-09-30:** 1.324800e+11 ($132.480 billion)

In [ ]:
question = "Apple Balance Sheet Total Assets Total Liabilities Current Liabilities Total Non Current Liabilities"

question_embedding = embedding_model.encode([question])

distances, indices = index.search(
    question_embedding.astype("float32"),
    k=5
)

for i in indices[0]:
    print("----- Retrieved Chunk -----")
    print(chunks[i])
    print()

----- Retrieved Chunk -----
Apple Balance Sheet
                                                       2025-09-30    2024-09-30    2023-09-30    2022-09-30
Treasury Shares Number                                        NaN           NaN  0.000000e+00           NaN
Ordinary Shares Number                               1.477326e+10  1.511679e+10  1.555006e+10  1.594342e+10
Share Issued                                         1.477326e+10  1.511679e+10  1.555006e+10  1.594342e+10
Net Debt                                             6.272300e+10  7.668600e+10  8.112300e+10  9.642300e+10
Total Debt                                           9.865700e+10  1.066290e+11  1.110880e+11  1.324800e+11
Tangible Book Value                                  7.373300e+10  5.695000e+10  6.214600e+10  5.067200e+10
Invested Capital                                     1.723900e+11  1.635790e+11  1.732340e+11  1.707410e+11
Working Capital                                     -1.767400e+10 -2.340500e+10 -1.742000e+09 -1.857700e+10

----- Retrieved Chunk -----
Apple Cash Flow Statement
                                                  2025-09-30    2024-09-30    2023-09-30    2022-09-30
Free Cash Flow                                  9.876700e+10  1.088070e+11  9.958400e+10  1.114430e+11
Repurchase Of Capital Stock                    -9.071100e+10 -9.494900e+10 -7.755000e+10 -8.940200e+10
Repayment Of Debt                              -1.093200e+10 -9.958000e+09 -1.115100e+10 -9.543000e+09
Issuance Of Debt                                4.481000e+09  0.000000e+00  5.228000e+09  5.465000e+09
Capital Expenditure                            -1.271500e+10 -9.447000e+09 -1.095900e+10 -1.070800e+10
Interest Paid Supplemental Data                          NaN           NaN  3.803000e+09  2.865000e+09
Income Tax Paid Supplemental Data               4.336900e+10  2.610200e+10  1.867900e+10  1.957300e+10
End Cash Position                               3.593400e+10  2.994300e+10  3.073700e+10  2.497700e+10

----- Retrieved Chunk -----
Apple Financial Metrics
          Metric        Value
      Market Cap 4.968151e+12
   Current Price 3.404200e+02
         Revenue 4.668230e+11
      Net Income 1.289300e+11
             EPS 8.720000e+00
       P/E Ratio 3.903899e+01
   Price to Book 4.625272e+01
Return on Equity 1.487510e+00
   Profit Margin 2.761900e-01
Operating Margin 3.262300e-01
  Debt to Equity 7.844500e+01
  Free Cash Flow 1.077219e+11

----- Retrieved Chunk -----
Apple Income Statement
                                                              2025-09-30    2024-09-30    2023-09-30    2022-09-30
Tax Effect Of Unusual Items                                 0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Tax Rate For Calcs                                          1.560000e-01  2.410000e-01  1.470000e-01  1.620000e-01
Normalized EBITDA                                           1.447480e+11  1.346610e+11  1.258200e+11  1.305410e+11
Net Income From Continuing Operation Net Minority Interest  1.120100e+11  9.373600e+10  9.699500e+10  9.980300e+10
Reconciled Depreciation                                     1.169800e+10  1.144500e+10  1.151900e+10  1.110400e+10
Reconciled Cost Of Revenue                                  2.209600e+11  2.103520e+11  2.141370e+11  2.235460e+11
EBITDA                                                      1.447480e+11  1.346610e+11  1.258200e+11  1.305410e+11

----- Retrieved Chunk -----
Other Equity Adjustments                            -5.571000e+09 -7.172000e+09 -1.145200e+10 -1.110900e+10
Retained Earnings                                   -1.426400e+10 -1.915400e+10 -2.140000e+08 -3.068000e+09
Capital Stock                                        9.356800e+10  8.327600e+10  7.381200e+10  6.484900e+10
Common Stock                                         9.356800e+10  8.327600e+10  7.381200e+10  6.484900e+10
Total Liabilities Net Minority Interest              2.855080e+11  3.080300e+11  2.904370e+11  3.020830e+11
Total Non Current Liabilities Net Minority Interest  1.198770e+11  1.316380e+11  1.451290e+11  1.481010e+11
Other Non Current Liabilities                        4.154900e+10  4.588800e+10  3.439100e+10  2.173700e+10
Tradeand Other Payables Non Current                           NaN  9.254000e+09  1.545700e+10  1.665700e+10
Long Term Debt And Capital Lease Obligation          7.832800e+10  8.575000e+10  9.528100e+10  1.097070e+11

In [ ]:
print("Total Assets:")
print(balance_sheet.loc["Total Assets"])

print("\nTotal Liabilities:")
print(balance_sheet.loc["Total Liabilities Net Minority Interest"])

Total Assets:
2025-09-30    3.592410e+11
2024-09-30    3.649800e+11
2023-09-30    3.525830e+11
2022-09-30    3.527550e+11
Name: Total Assets, dtype: float64

Total Liabilities:
2025-09-30    2.855080e+11
2024-09-30    3.080300e+11
2023-09-30    2.904370e+11
2022-09-30    3.020830e+11
Name: Total Liabilities Net Minority Interest, dtype: float64

In [ ]:
question = "What is Apple's operating cash flow for 2022, 2023, 2024, and 2025?"

question_embedding = embedding_model.encode([question])

distances, indices = index.search(
    question_embedding.astype("float32"),
    k=5
)

for i in indices[0]:
    print("----- Retrieved Chunk -----")
    print(chunks[i])
    print()

----- Retrieved Chunk -----
Apple Financial Metrics
          Metric        Value
      Market Cap 4.968151e+12
   Current Price 3.404200e+02
         Revenue 4.668230e+11
      Net Income 1.289300e+11
             EPS 8.720000e+00
       P/E Ratio 3.903899e+01
   Price to Book 4.625272e+01
Return on Equity 1.487510e+00
   Profit Margin 2.761900e-01
Operating Margin 3.262300e-01
  Debt to Equity 7.844500e+01
  Free Cash Flow 1.077219e+11

----- Retrieved Chunk -----
Apple Cash Flow Statement
                                                  2025-09-30    2024-09-30    2023-09-30    2022-09-30
Free Cash Flow                                  9.876700e+10  1.088070e+11  9.958400e+10  1.114430e+11
Repurchase Of Capital Stock                    -9.071100e+10 -9.494900e+10 -7.755000e+10 -8.940200e+10
Repayment Of Debt                              -1.093200e+10 -9.958000e+09 -1.115100e+10 -9.543000e+09
Issuance Of Debt                                4.481000e+09  0.000000e+00  5.228000e+09  5.465000e+09
Capital Expenditure                            -1.271500e+10 -9.447000e+09 -1.095900e+10 -1.070800e+10
Interest Paid Supplemental Data                          NaN           NaN  3.803000e+09  2.865000e+09
Income Tax Paid Supplemental Data               4.336900e+10  2.610200e+10  1.867900e+10  1.957300e+10
End Cash Position                               3.593400e+10  2.994300e+10  3.073700e+10  2.497700e+10

----- Retrieved Chunk -----
Apple Balance Sheet
                                                       2025-09-30    2024-09-30    2023-09-30    2022-09-30
Treasury Shares Number                                        NaN           NaN  0.000000e+00           NaN
Ordinary Shares Number                               1.477326e+10  1.511679e+10  1.555006e+10  1.594342e+10
Share Issued                                         1.477326e+10  1.511679e+10  1.555006e+10  1.594342e+10
Net Debt                                             6.272300e+10  7.668600e+10  8.112300e+10  9.642300e+10
Total Debt                                           9.865700e+10  1.066290e+11  1.110880e+11  1.324800e+11
Tangible Book Value                                  7.373300e+10  5.695000e+10  6.214600e+10  5.067200e+10
Invested Capital                                     1.723900e+11  1.635790e+11  1.732340e+11  1.707410e+11
Working Capital                                     -1.767400e+10 -2.340500e+10 -1.742000e+09 -1.857700e+10

----- Retrieved Chunk -----
Apple Historical Performance
              Open         High          Low        Close        Volume    Dividends  Stock Splits
count  1254.000000  1254.000000  1254.000000  1254.000000  1.254000e+03  1254.000000        1254.0
mean    203.315315   205.578726   201.312992   203.552578  6.335963e+07     0.003907           0.0
std      51.790739    52.277757    51.381060    51.870949  2.858368e+07     0.030764           0.0
min     123.800267   125.529397   121.992536   122.827621  1.791060e+07     0.000000           0.0
25%     163.719221   165.466764   162.345993   163.650394  4.470120e+07     0.000000           0.0
50%     189.140595   191.097134   187.890451   189.338287  5.486660e+07     0.000000           0.0
75%     235.620123   238.452066   232.682001   235.871006  7.491310e+07     0.000000           0.0
max     341.079987   345.339996   338.750000   341.070007  3.186799e+08     0.270000           0.0

----- Retrieved Chunk -----
Apple Income Statement
                                                              2025-09-30    2024-09-30    2023-09-30    2022-09-30
Tax Effect Of Unusual Items                                 0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Tax Rate For Calcs                                          1.560000e-01  2.410000e-01  1.470000e-01  1.620000e-01
Normalized EBITDA                                           1.447480e+11  1.346610e+11  1.258200e+11  1.305410e+11
Net Income From Continuing Operation Net Minority Interest  1.120100e+11  9.373600e+10  9.699500e+10  9.980300e+10
Reconciled Depreciation                                     1.169800e+10  1.144500e+10  1.151900e+10  1.110400e+10
Reconciled Cost Of Revenue                                  2.209600e+11  2.103520e+11  2.141370e+11  2.235460e+11
EBITDA                                                      1.447480e+11  1.346610e+11  1.258200e+11  1.305410e+11

In [ ]:
print("Operating Cash Flow:")
print(cash_flow.loc["Operating Cash Flow"])

Operating Cash Flow:
2025-09-30    1.114820e+11
2024-09-30    1.182540e+11
2023-09-30    1.105430e+11
2022-09-30    1.221510e+11
Name: Operating Cash Flow, dtype: float64

In [ ]:
operating_cash_flow_text = cash_flow.loc["Operating Cash Flow"].to_string()

financial_documents.append({
    "title": "Apple Operating Cash Flow",
    "content": operating_cash_flow_text
})

all_text = ""

for document in financial_documents:
    all_text += document["title"] + "\n"
    all_text += document["content"] + "\n\n"

chunks = text_splitter.split_text(all_text)

embeddings = embedding_model.encode(chunks)

dimension = embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(embeddings.astype("float32"))

print("Number of chunks:", len(chunks))
print("Number of vectors in FAISS:", index.ntotal)

Number of chunks: 24
Number of vectors in FAISS: 24

In [ ]:
question = "What is Apple's operating cash flow for 2022, 2023, 2024, and 2025?"

question_embedding = embedding_model.encode([question])

distances, indices = index.search(
    question_embedding.astype("float32"),
    k=3
)

for i in indices[0]:
    print("----- Retrieved Chunk -----")
    print(chunks[i])
    print()

----- Retrieved Chunk -----
Apple Financial Metrics
          Metric        Value
      Market Cap 4.968151e+12
   Current Price 3.404200e+02
         Revenue 4.668230e+11
      Net Income 1.289300e+11
             EPS 8.720000e+00
       P/E Ratio 3.903899e+01
   Price to Book 4.625272e+01
Return on Equity 1.487510e+00
   Profit Margin 2.761900e-01
Operating Margin 3.262300e-01
  Debt to Equity 7.844500e+01
  Free Cash Flow 1.077219e+11

Apple Operating Cash Flow
2025-09-30    1.114820e+11
2024-09-30    1.182540e+11
2023-09-30    1.105430e+11
2022-09-30    1.221510e+11

----- Retrieved Chunk -----
Apple Cash Flow Statement
                                                  2025-09-30    2024-09-30    2023-09-30    2022-09-30
Free Cash Flow                                  9.876700e+10  1.088070e+11  9.958400e+10  1.114430e+11
Repurchase Of Capital Stock                    -9.071100e+10 -9.494900e+10 -7.755000e+10 -8.940200e+10
Repayment Of Debt                              -1.093200e+10 -9.958000e+09 -1.115100e+10 -9.543000e+09
Issuance Of Debt                                4.481000e+09  0.000000e+00  5.228000e+09  5.465000e+09
Capital Expenditure                            -1.271500e+10 -9.447000e+09 -1.095900e+10 -1.070800e+10
Interest Paid Supplemental Data                          NaN           NaN  3.803000e+09  2.865000e+09
Income Tax Paid Supplemental Data               4.336900e+10  2.610200e+10  1.867900e+10  1.957300e+10
End Cash Position                               3.593400e+10  2.994300e+10  3.073700e+10  2.497700e+10

----- Retrieved Chunk -----
Apple Balance Sheet
                                                       2025-09-30    2024-09-30    2023-09-30    2022-09-30
Treasury Shares Number                                        NaN           NaN  0.000000e+00           NaN
Ordinary Shares Number                               1.477326e+10  1.511679e+10  1.555006e+10  1.594342e+10
Share Issued                                         1.477326e+10  1.511679e+10  1.555006e+10  1.594342e+10
Net Debt                                             6.272300e+10  7.668600e+10  8.112300e+10  9.642300e+10
Total Debt                                           9.865700e+10  1.066290e+11  1.110880e+11  1.324800e+11
Tangible Book Value                                  7.373300e+10  5.695000e+10  6.214600e+10  5.067200e+10
Invested Capital                                     1.723900e+11  1.635790e+11  1.732340e+11  1.707410e+11
Working Capital                                     -1.767400e+10 -2.340500e+10 -1.742000e+09 -1.857700e+10

In [ ]:
question = "What is Apple's historical stock price performance over the last five years?"

question_embedding = embedding_model.encode([question])

distances, indices = index.search(
    question_embedding.astype("float32"),
    k=3
)

for i in indices[0]:
    print("----- Retrieved Chunk -----")
    print(chunks[i])
    print()

----- Retrieved Chunk -----
Apple Historical Performance
              Open         High          Low        Close        Volume    Dividends  Stock Splits
count  1254.000000  1254.000000  1254.000000  1254.000000  1.254000e+03  1254.000000        1254.0
mean    203.315315   205.578726   201.312992   203.552578  6.335963e+07     0.003907           0.0
std      51.790739    52.277757    51.381060    51.870949  2.858368e+07     0.030764           0.0
min     123.800267   125.529397   121.992536   122.827621  1.791060e+07     0.000000           0.0
25%     163.719221   165.466764   162.345993   163.650394  4.470120e+07     0.000000           0.0
50%     189.140595   191.097134   187.890451   189.338287  5.486660e+07     0.000000           0.0
75%     235.620123   238.452066   232.682001   235.871006  7.491310e+07     0.000000           0.0
max     341.079987   345.339996   338.750000   341.070007  3.186799e+08     0.270000           0.0

----- Retrieved Chunk -----
Apple Financial Metrics
          Metric        Value
      Market Cap 4.968151e+12
   Current Price 3.404200e+02
         Revenue 4.668230e+11
      Net Income 1.289300e+11
             EPS 8.720000e+00
       P/E Ratio 3.903899e+01
   Price to Book 4.625272e+01
Return on Equity 1.487510e+00
   Profit Margin 2.761900e-01
Operating Margin 3.262300e-01
  Debt to Equity 7.844500e+01
  Free Cash Flow 1.077219e+11

Apple Operating Cash Flow
2025-09-30    1.114820e+11
2024-09-30    1.182540e+11
2023-09-30    1.105430e+11
2022-09-30    1.221510e+11

----- Retrieved Chunk -----
Apple Balance Sheet
                                                       2025-09-30    2024-09-30    2023-09-30    2022-09-30
Treasury Shares Number                                        NaN           NaN  0.000000e+00           NaN
Ordinary Shares Number                               1.477326e+10  1.511679e+10  1.555006e+10  1.594342e+10
Share Issued                                         1.477326e+10  1.511679e+10  1.555006e+10  1.594342e+10
Net Debt                                             6.272300e+10  7.668600e+10  8.112300e+10  9.642300e+10
Total Debt                                           9.865700e+10  1.066290e+11  1.110880e+11  1.324800e+11
Tangible Book Value                                  7.373300e+10  5.695000e+10  6.214600e+10  5.067200e+10
Invested Capital                                     1.723900e+11  1.635790e+11  1.732340e+11  1.707410e+11
Working Capital                                     -1.767400e+10 -2.340500e+10 -1.742000e+09 -1.857700e+10

In [ ]:
first_price = historical_data["Close"].iloc[0]
last_price = historical_data["Close"].iloc[-1]

price_change = last_price - first_price
percentage_change = (price_change / first_price) * 100

print("First closing price:", round(first_price, 2))
print("Latest closing price:", round(last_price, 2))
print("Price change:", round(price_change, 2))
print("Percentage change:", round(percentage_change, 2), "%")

First closing price: 139.29
Latest closing price: 340.42
Price change: 201.13
Percentage change: 144.39 %